image: node:16

options:
 max-time: 20
pipelines:
  branches:
    master:
      - step:
          name: Install Dependencies & Build Project
          size: 2x
          caches:
            - node
          script:
            - npm install -f
            - export NODE_OPTIONS=--max-old-space-size=4096
            - CI=false npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to master
          script:
            - scp -pvr build/* cbdev@147.182.160.178:/var/www/html/tokenmaker_admin